#%RAML 1.0
---
title: Stockturn API
version: v1
mediaType: application/json

types:
    Response404:
        type: object
        properties:
            message:
                description: "Feedback message"
                required: true
                type: string

    Pageable:
        type: object
        properties:
            from:
                description: "Previous page number"
                required: true
                type: number
            to:
                description: "Next page number"
                required: true
                type: number
            current_page:
                description: "Current page number"
                required: true
                type: number
            last_page:
                description: "Last page number"
                required: true
                type: number
            first_page_url:
                description: "First page URL"
                required: true
                type: string
            last_page_url:
                description: "Last page URL"
                required: true
                type: string
            prev_page_url:
                description: "Previous page URL"
                required: true
                type: string
            next_page_url:
                description: "Next page URL"
                required: true
                type: string
            links: Link[]
            path:
                description: "Current page path (without query parameters)"
                required: true
                type: string
            per_page:
                description: "Maximum of returned items per page"
                required: true
                type: number
            total:
                description: "Total pages quantity"
                required: true
                type: number

    Link:
        type: object
        properties:
            url:
                description: "Link URL"
                required: false
                type: string
            label:
                description: "Link label"
                required: true
                type: string
            active:
                description: "Link is active"
                required: true
                type: boolean

    Product:
        type: object
        properties:
            id:
                description: "Product ID"
                required: true
                type: integer
            name:
                description: "Product name"
                required: true
                type: string
            sku:
                description: "Product sku"
                required: true
                type: string
            price:
                description: "Product price"
                required: true
                type: number
            stock:
                description: "Product stock quantity"
                required: true
                type: integer
            stockTimeline:
                description: "Stock timeline"
                required: true
                type: StockTimeline
            created_at:
                description: "Product creation date"
                required: true
                type: datetime
            updated_at:
                description: "Product last update date"
                required: true
                type: datetime

    ProductsPageable:
        type: Pageable
        properties:
            data:
                description: "Data content"
                required: true
                type: Product[]

    ProductCreate:
        type: object
        properties:
            name:
                description: "Product name"
                required: true
                type: string
            price:
                description: "Product price"
                required: true
                type: number
            stock:
                description: "Product stock quantity"
                required: false
                type: integer

    ProductUpdate:
        type: object
        properties:
            id:
                description: "Product id"
                required: true
                type: integer
            name:
                description: "Product name"
                required: false
                type: string
            price:
                description: "Product price"
                required: false
                type: number
            stock:
                description: "Product stock quantity"
                required: false
                type: integer

    Upload:
        type:  object
        properties:
            id:
                description: "Upload id"
                required: true
                type: integer
            path:
                description: "Upload path"
                required: false
                type: string
            size:
                description: "Upload size"
                required: true
                type: number
            type:
                description: "Upload type"
                required: true
                type: string
            status:
                description: "Upload status"
                required: true
                type: string
            message:
                description: "Upload message"
                required: false
                type: string
            created_at:
                description: "Product creation date"
                required: true
                type: datetime
            updated_at:
                description: "Product last update date"
                required: true
                type: datetime

    UploadsPageable:
        type: Pageable
        properties:
            data:
                description: "Data content"
                required: true
                type: Upload[]

    UploadCreate:
        type: object
        properties:
            file:
                description: "File"
                required: true
                type: file

    StockTimeline:
        type: object
        properties:
            stock:
                description: "Timeline item stock quantity"
                required: true
                type: number
            date:
                description: "Timeline item date"
                required: true
                type: datetime-only

traits:
    has404:
        responses:
            404:
                description: "Not found"
                body:
                    application/json:
                        type: Response404
                        example: |
                            {
                                "message": "Not Found"
                            }

/products:
    description: "Products resource"

    /:
        get:
            description: "Get a list of products"
            queryParameters:
                name:
                    description: "Product name"
                    required: false
                    type: string
                    example: "Produto A"
                sku:
                    description: "Product sku"
                    required: false
                    type: string
                    example: "fd5fac04-f4af-4c02-b7ec-0d0d0c50af78"
                fromPrice:
                    description: "Minimum price"
                    required: false
                    type: number
                    example: 5.00
                toPrice:
                    description: "Maximum price"
                    required: false
                    type: number
                    example: 10.99
                fromStock:
                    description: "Minimum stock"
                    required: false
                    type: integer
                    example: 5
                toStock:
                    description: "Maximum stock"
                    required: false
                    type: integer
                    example: 10
                fromDate:
                    description: "Minimum creation date (format: yyyy-mm-dd)"
                    required: false
                    type: string
                    example: "2021-02-01"
                toDate:
                    description: "Maximum creation date (format: yyyy-mm-dd)"
                    required: false
                    type: string
                    example: "2021-02-15"
                page:
                    description: "Page number"
                    required: false
                    default: 1
                    type: integer
                    example: 2
                sort:
                    description: "Property to sort result (format: property_name:[asc/desc])"
                    required: false
                    default: id:asc
                    type: string
                    example: "price:desc"
            responses:
                200:
                    description: "Products list"
                    body:
                        application/json:
                            type: ProductsPageable
                            example: !include examples/productsPageable.json

        post:
            description: "Create new product"
            body:
                type: ProductCreate
                example: !include examples/productCreate.json
            responses:
                201:
                    description: "Product created"
                    body:
                        application/json:
                            type: Product
                            example: !include examples/product.json

    /{productId}:
        uriParameters:
            productId:
                description: "Product ID"
                type: integer

        get:
            description: "Get a product"
            is: [ has404 ]
            responses:
                200:
                    description: "Product show"
                    body:
                        application/json:
                            type: Product
                            example: !include examples/product.json

        put:
            description: "Update a product"
            is: [ has404 ]
            body:
                type: ProductUpdate
                example: !include examples/productUpdate.json
            responses:
                200:
                    description: "Product updated"
                    body:
                        application/json:
                            type: Product
                            example: !include examples/product.json

        delete:
            description: "Delete a product"
            responses:
                204:
                    description: "Product deleted"

/uploads:
    description: "Uploads resource"

    /:
        get:
            description: "Get a list of uploads"
            responses:
                200:
                    description: "Uploads list"
                    body:
                        application/json:
                            type: UploadsPageable
                            example: !include examples/uploadsPageable.json

        post:
            description: "Create new upload (Upload file)"
            body:
                type: UploadCreate
            responses:
                201:
                    description: "Upload created"
                    body:
                        application/json:
                            type: Upload
                            example: !include examples/upload.json
