#%RAML 1.0
---
title: Products API
version: v1
mediaType: application/json

types:
    Response404:
        type: object
        properties:
            message:
                description: "Feedback message"
                required: true
                type: string

    Pageable:
        type: object
        properties:
            data:
                description: "Data content"
                required: true
                type: Product[]
            from:
                description: "Previous page number"
                required: true
                type: number
            to:
                description: "Next page number"
                required: true
                type: number
            current_page:
                description: "Current page number"
                required: true
                type: number
            last_page:
                description: "Last page number"
                required: true
                type: number
            first_page_url:
                description: "First page URL"
                required: true
                type: string
            last_page_url:
                description: "Last page URL"
                required: true
                type: string
            prev_page_url:
                description: "Previous page URL"
                required: true
                type: string
            next_page_url:
                description: "Next page URL"
                required: true
                type: string
            links: Link[]
            path:
                description: "Current page path (without query parameters)"
                required: true
                type: string
            per_page:
                description: "Maximum of returned items per page"
                required: true
                type: number
            total:
                description: "Total pages quantity"
                required: true
                type: number

    Link:
        type: object
        properties:
            url:
                description: "Link URL"
                required: false
                type: string
            label:
                description: "Link label"
                required: true
                type: string
            active:
                description: "Link is active"
                required: true
                type: boolean

    Product:
        type: object
        properties:
            id:
                description: "Product ID"
                required: false
                type: number
            name:
                description: "Product name"
                required: true
                type: string
            sku:
                description: "Product sku"
                required: true
                unique: true
                type: string
            price:
                description: "Product price"
                required: true
                type: number
            stock:
                description: "Product stock quantity"
                required: true
                type: number
            stockTimeline:
                description: "Stock timeline"
                required: false
                type: StockTimeline
            # created_at:
            #     description: "Product creation date"
            #     required: false
            #     type: datetime
            # updated_at:
            #     description: "Product last update date"
            #     required: false
            #     type: datetime

    StockTimeline:
        type: object
        properties:
            stock:
                description: "Timeline item stock quantity"
                required: true
                type: number
            date:
                description: "Timeline item date"
                required: true
                type: datetime-only

traits:
    has404:
        responses:
            404:
                description: "Not found"
                body:
                    application/json:
                        type: Response404
                        example: |
                            {
                                "message": "Not Found"
                            }

/products:
    get:
        description: "List products"
        queryParameters:
            name:
                description: "Product name"
                required: false
                type: string
                example: "Produto A"
            sku:
                description: "Product sku"
                required: false
                type: string
                example: "fd5fac04-f4af-4c02-b7ec-0d0d0c50af78"
            fromPrice:
                description: "Minimum price"
                required: false
                type: number
                example: 5.00
            toPrice:
                description: "Maximum price"
                required: false
                type: number
                example: 10.99
            fromDate:
                description: "Minimum creation date (format: yyyy-mm-dd)"
                required: false
                type: string
                example: "2021-02-01"
            toDate:
                description: "Maximum creation date (format: yyyy-mm-dd)"
                required: false
                type: string
                example: "2021-02-15"
            page:
                description: "Page number"
                required: false
                default: 1
                type: number
                example: 2
            sort:
                description: "Property to sort result (format: property_name:[asc/desc])"
                required: false
                default: id:asc
                type: string
                example: "price:desc"
        responses:
            200:
                description: "Products list"
                body:
                    application/json:
                        type: Pageable
                        example: |
                            {
                                "current_page": 1,
                                "data": [
                                    {
                                        "id": 8,
                                        "name": "Product 477",
                                        "sku": "603e4dd829f9c",
                                        "price": 690.53,
                                        "stock": 23,
                                        "stockTimeline": [
                                            {
                                                "stock": 90,
                                                "date": "2021-01-10 04:43"
                                            },
                                            {
                                                "stock": 55,
                                                "date": "2021-01-11 15:13"
                                            },
                                            {
                                                "stock": 35,
                                                "date": "2021-01-11 19:55"
                                            },
                                            {
                                                "stock": 19,
                                                "date": "2021-01-21 19:33"
                                            },
                                            {
                                                "stock": 28,
                                                "date": "2021-02-04 00:16"
                                            },
                                            {
                                                "stock": 24,
                                                "date": "2021-02-10 06:22"
                                            },
                                            {
                                                "stock": 50,
                                                "date": "2021-02-26 00:46"
                                            },
                                            {
                                                "stock": 27,
                                                "date": "2021-02-28 20:00"
                                            }
                                        ],
                                        "created_at": "2021-03-02T14:38:16.000000Z",
                                        "updated_at": "2021-03-02T14:38:16.000000Z"
                                    },
                                    {
                                        "id": 4,
                                        "name": "Product 796",
                                        "sku": "603e4dd829bf4",
                                        "price": 509.07,
                                        "stock": 80,
                                        "stockTimeline": [
                                            {
                                                "stock": 82,
                                                "date": "2021-01-02 17:42"
                                            },
                                            {
                                                "stock": 57,
                                                "date": "2021-01-03 18:51"
                                            },
                                            {
                                                "stock": 51,
                                                "date": "2021-01-10 19:13"
                                            },
                                            {
                                                "stock": 64,
                                                "date": "2021-01-30 21:54"
                                            },
                                            {
                                                "stock": 88,
                                                "date": "2021-02-05 08:49"
                                            },
                                            {
                                                "stock": 16,
                                                "date": "2021-02-07 09:03"
                                            },
                                            {
                                                "stock": 74,
                                                "date": "2021-02-20 23:51"
                                            },
                                            {
                                                "stock": 41,
                                                "date": "2021-02-21 05:15"
                                            }
                                        ],
                                        "created_at": "2021-03-02T14:38:16.000000Z",
                                        "updated_at": "2021-03-02T14:38:16.000000Z"
                                    }
                                ],
                                "first_page_url": "http://api.local.test:8001/api/products?page=1",
                                "from": 1,
                                "last_page": 1,
                                "last_page_url": "http://api.local.test:8001/api/products?page=1",
                                "links": [
                                    {
                                        "url": null,
                                        "label": "&laquo; Previous",
                                        "active": false
                                    },
                                    {
                                        "url": "http://api.local.test:8001/api/products?page=1",
                                        "label": "1",
                                        "active": true
                                    },
                                    {
                                        "url": null,
                                        "label": "Next &raquo;",
                                        "active": false
                                    }
                                ],
                                "next_page_url": null,
                                "path": "http://api.local.test:8001/api/products",
                                "per_page": "3",
                                "prev_page_url": null,
                                "to": 2,
                                "total": 2
                            }

    post:
        description: "Create new product"
        body:
            type: Product

/products/{productId}:
    get:
        description: "Get a product"
        is: [ has404 ]

    put:
        description: "Update a product"
        is: [ has404 ]

    delete:
        description: "Delete a product"
